### PR TITLE
Engine reset

### PR DESCRIPTION
**Pull request by bglusman**
Merging history with engine repo with a reset soft, and pull in README from master

### CODE REVIEW

**Comment by bglusman** [comment]
@catmando I'll let you merge this in or discuss if you want further changes, like I dunno if you care about third-rail and third_rail differences..  Maybe I'll fork the todo app repo here though later today and start playing.

**Comment by bglusman** [comment]
@catmando did you want me to merge this in myself, or did you want to dicuss/wait on decisions for other changes?

**Comment by catmando** [comment]
Merge on brother

**Comment by catmando** [comment]
Cool

**Pull request merged**
